# Generated by Django 4.2.7 on 2023-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
